title: Porfolio1
email: jiachen.e.c@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /Portfolio1

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
- old
- vendor/bundle/
defaults:
  - scope:
      path: "assets/mcon"
    values:
      image: true
