title: Porfolio1
email: jiachen.e.c@gmail.com
description: Jiachen's Design Portfolio, built with Jekyll
baseurl: /Portfolio1

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
- old
- vendor/bundle/
